name: test

on:
  push:

env:
  FOUNDRY_PROFILE: ci

jobs:
  reproduce-on-mac:
    strategy:
      fail-fast: true

    name: Reproduce issue on macos12
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install forge-std
        run: forge install --no-commit foundry-rs/forge-std

      - name: Mess up by manually removing the lib/forge-std directory
        run: rm -rf lib/forge-std

      - name: Try to reinstall
        run: forge install --no-commit foundry-rs/forge-std
        if: always()

      - name: Mess up even more by removing lib/forge-std from the staging area
        run: git add lib/forge-std
        if: always()

      - name: Try to remove
        run: forge remove lib/forge-std
        if: always()

      - name: Try to update
        run: forge update lib/forge-std
        if: always()

